#pragma once

#ifndef FF_INPUT_BUFFER_PADDING_SIZE
#ifdef AV_INPUT_BUFFER_PADDING_SIZE
#define FF_INPUT_BUFFER_PADDING_SIZE AV_INPUT_BUFFER_PADDING_SIZE
#endif
#endif

#ifndef CODEC_CAP_DR1
#ifdef AV_CODEC_CAP_DR1
#define CODEC_CAP_DR1 AV_CODEC_CAP_DR1
#endif
#endif

#ifndef CODEC_CAP_TRUNCATED
#ifdef AV_CODEC_CAP_TRUNCATED
#define CODEC_CAP_TRUNCATED AV_CODEC_CAP_TRUNCATED
#endif
#endif

#if !defined(CODEC_FLAG_EMU_EDGE) && defined(AV_CODEC_FLAG_EMU_EDGE)
#define CODEC_FLAG_EMU_EDGE AV_CODEC_FLAG_EMU_EDGE
#endif

#if !defined(CODEC_FLAG_TRUNCATED) && defined(AV_CODEC_FLAG_TRUNCATED)
#define CODEC_FLAG_TRUNCATED AV_CODEC_FLAG_TRUNCATED
#endif

#ifndef FF_QSCALE_TYPE_MPEG1
#define FF_QSCALE_TYPE_MPEG1 0
#endif

#ifndef FF_QSCALE_TYPE_MPEG2
#define FF_QSCALE_TYPE_MPEG2 1
#endif

#ifndef FF_QSCALE_TYPE_H264
#define FF_QSCALE_TYPE_H264 2
#endif
