package org.github.krkr2

import android.content.Context

object LauncherStrings {
    data class Texts(
        val title: String,
        val grantStorage: String,
        val settings: String,
        val scan: String,
        val gameRootPath: String,
        val saveAndScan: String,
        val reloadSaved: String,
        val start: String,
        val noGamesFound: String,
        val emptyHint: String,
        val launchOriginal: String,
        val language: String,
        val english: String,
        val chinese: String,
        val save: String,
        val forceLandscape: String,
        val stats: String,
        val launches: String,
        val playTime: String,
        val alias: String,
        val exportBackup: String,
        val exported: String,
        val customImagePath: String,
        val close: String,
        val diagnostics: String,
        val diagnosticsTitle: String,
        val appVersion: String,
        val appBuildId: String,
        val appAbi: String,
        val nativeFatalLog: String,
        val launcherLog: String,
        val noFatalLog: String,
        val noLauncherLog: String,
        val copy: String,
        val copied: String,
        val share: String,
        val refresh: String,
        val clear: String,
        val cleared: String,
        val grantWriteSettings: String,
        val writeSettingsGranted: String,
        val writeSettingsHint: String,
    )

    fun current(context: Context): Texts = if (LauncherPrefs.getLanguage(context) == LauncherPrefs.LANG_ZH) zh else en

    val en = Texts(
        title = "KrKr2 Launcher",
        grantStorage = "Grant Storage",
        settings = "Settings",
        scan = "Scan",
        gameRootPath = "Game root path",
        saveAndScan = "Save & Scan",
        reloadSaved = "Reload Saved",
        start = "Start",
        noGamesFound = "No games found",
        emptyHint = "Type the correct game folder path above, then scan.",
        launchOriginal = "Launch original KRKR",
        language = "Language",
        english = "English",
        chinese = "中文",
        save = "Save",
        forceLandscape = "Force landscape",
        stats = "Stats",
        launches = "Launches",
        playTime = "Play time",
        alias = "Alias",
        exportBackup = "Export backup",
        exported = "Exported",
        customImagePath = "Custom image path",
        close = "Close",
        diagnostics = "Diagnostics",
        diagnosticsTitle = "Diagnostics",
        appVersion = "App version",
        appBuildId = "Native BuildID",
        appAbi = "ABI",
        nativeFatalLog = "Native fatal log",
        launcherLog = "Launcher log (last 200 lines)",
        noFatalLog = "(no native fatal log yet)",
        noLauncherLog = "(no launcher log)",
        copy = "Copy",
        copied = "Copied",
        share = "Share",
        refresh = "Refresh",
        clear = "Clear",
        cleared = "Cleared",
        grantWriteSettings = "Grant rotation control",
        writeSettingsGranted = "Granted",
        writeSettingsHint = "Required to truly lock landscape on OEMs that ignore the activity-level lock (vivo / OPPO / MIUI). Without it, the system rotation lock can still flip the screen.",
    )

    val zh = Texts(
        title = "KrKr2 启动器",
        grantStorage = "授权存储",
        settings = "设置",
        scan = "扫描",
        gameRootPath = "游戏根目录路径",
        saveAndScan = "保存并扫描",
        reloadSaved = "重新加载保存路径",
        start = "启动",
        noGamesFound = "没有找到游戏",
        emptyHint = "请在上方输入正确的游戏目录，然后扫描。",
        launchOriginal = "启动 KRKR 原版",
        language = "语言",
        english = "English",
        chinese = "中文",
        save = "保存",
        forceLandscape = "强制横屏",
        stats = "统计",
        launches = "启动次数",
        playTime = "游玩时长",
        alias = "别名",
        exportBackup = "导出备份",
        exported = "已导出",
        customImagePath = "自定义图片路径",
        close = "关闭",
        diagnostics = "诊断",
        diagnosticsTitle = "诊断面板",
        appVersion = "应用版本",
        appBuildId = "Native BuildID",
        appAbi = "ABI 架构",
        nativeFatalLog = "Native 崩溃日志",
        launcherLog = "启动器日志（最近 200 行）",
        noFatalLog = "（暂无 native 崩溃日志）",
        noLauncherLog = "（暂无启动器日志）",
        copy = "复制",
        copied = "已复制",
        share = "分享",
        refresh = "刷新",
        clear = "清空",
        cleared = "已清空",
        grantWriteSettings = "授权旋转控制",
        writeSettingsGranted = "已授权",
        writeSettingsHint = "在 vivo / OPPO / 小米等系统上，仅靠 Activity 级横屏锁定不够，必须临时关闭系统自动旋转才能真正锁住。授权后即可绕过系统旋转锁。",
    )
}