package org.github.krkr2

import android.content.Context
import org.github.krkr2.data.TimeFormat

/**
 * Static text bundles for the launcher. Two locales (EN/ZH) are bundled
 * inline so we don't need to ship strings.xml for every Compose-only string.
 *
 * Field set is aligned with KrKr2-Next's `AppLocalizations` so the UI layer
 * can use the same vocabulary.
 */
object LauncherStrings {
    data class Texts(
        // Brand / chrome
        val title: String,
        val settings: String,
        val grantStorage: String,
        // Library
        val noGamesYet: String,
        val noGamesHint: String,
        val addGame: String,
        val refresh: String,
        // Game card / detail
        val launchGame: String,
        val openInLauncher: String,
        val launches: String,
        val playTime: String,
        val lastPlayed: String,
        override val never: String,
        val xp3Archive: String,
        val directory: String,
        val location: String,
        val developer: String,
        val statsLabel: String,
        // Actions
        val rename: String,
        val setCover: String,
        val clearCover: String,
        val remove: String,
        val cancel: String,
        val save: String,
        val close: String,
        val confirmRemoveTitle: String,
        val confirmRemoveBody: String,
        // Settings sections
        val sectionAppearance: String,
        val sectionLibrary: String,
        val sectionDebug: String,
        val sectionAbout: String,
        val language: String,
        val english: String,
        val chinese: String,
        val forceLandscape: String,
        val gameRootPath: String,
        val logPath: String,
        val saveAndScan: String,
        val scanDone: String,
        val exportBackup: String,
        val exportLogs: String,
        val exported: String,
        val logsExported: String,
        val launchOriginal: String,
        // Time formatter
        override val justNow: String,
        val minutesAgoFmt: (Int) -> String,
        val hoursAgoFmt: (Int) -> String,
        val daysAgoFmt: (Int) -> String,
        // Misc
        val aboutVersion: String,
        val aboutDescription: String,
    ) : TimeFormat.Strings {
        override fun minutesAgo(n: Int): String = minutesAgoFmt(n)
        override fun hoursAgo(n: Int): String = hoursAgoFmt(n)
        override fun daysAgo(n: Int): String = daysAgoFmt(n)
    }

    fun current(context: Context): Texts =
        if (LauncherPrefs.getLanguage(context) == LauncherPrefs.LANG_ZH) zh else en

    val en = Texts(
        title = "KrKr2 Launcher",
        settings = "Settings",
        grantStorage = "Grant Storage",
        noGamesYet = "No games yet",
        noGamesHint = "Open Settings, set the game root path, then return to rescan.",
        addGame = "Add game",
        refresh = "Refresh",
        launchGame = "Launch Game",
        openInLauncher = "Open in launcher",
        launches = "Launches",
        playTime = "Play time",
        lastPlayed = "Last played",
        never = "Never",
        xp3Archive = "XP3 Archive",
        directory = "Directory",
        location = "Location",
        developer = "Developer",
        statsLabel = "Statistics",
        rename = "Rename",
        setCover = "Set cover",
        clearCover = "Clear cover",
        remove = "Remove",
        cancel = "Cancel",
        save = "Save",
        close = "Close",
        confirmRemoveTitle = "Remove from library?",
        confirmRemoveBody = "This only removes the entry from the launcher. Files on disk are kept.",
        sectionAppearance = "Appearance",
        sectionLibrary = "Library",
        sectionDebug = "Debug",
        sectionAbout = "About",
        language = "Language",
        english = "English",
        chinese = "中文",
        forceLandscape = "Force landscape",
        gameRootPath = "Game root path",
        logPath = "Log export path",
        saveAndScan = "Save",
        scanDone = "Saved. Returning to the home page will rescan.",
        exportBackup = "Export settings backup",
        exportLogs = "Export logs",
        exported = "Exported",
        logsExported = "Logs exported",
        launchOriginal = "Launch original KrKr2",
        justNow = "just now",
        minutesAgoFmt = { n -> "$n min ago" },
        hoursAgoFmt = { n -> "$n hr ago" },
        daysAgoFmt = { n -> "$n day${if (n == 1) "" else "s"} ago" },
        aboutVersion = "Build channel: launcher rework",
        aboutDescription = "Lightweight Android launcher for KrKr2 / Kirikiri engines.",
    )

    val zh = Texts(
        title = "KrKr2 启动器",
        settings = "设置",
        grantStorage = "授权存储",
        noGamesYet = "暂无游戏",
        noGamesHint = "请在设置中配置游戏根目录，返回主页后会自动重新扫描。",
        addGame = "添加游戏",
        refresh = "刷新",
        launchGame = "开始游戏",
        openInLauncher = "用启动器打开",
        launches = "启动次数",
        playTime = "游玩时长",
        lastPlayed = "上次游玩",
        never = "从未",
        xp3Archive = "XP3 归档",
        directory = "目录",
        location = "位置",
        developer = "开发商",
        statsLabel = "统计",
        rename = "重命名",
        setCover = "设置封面",
        clearCover = "清除封面",
        remove = "从库中移除",
        cancel = "取消",
        save = "保存",
        close = "关闭",
        confirmRemoveTitle = "从库中移除？",
        confirmRemoveBody = "仅从启动器中移除条目，磁盘文件不会被删除。",
        sectionAppearance = "外观",
        sectionLibrary = "游戏库",
        sectionDebug = "调试",
        sectionAbout = "关于",
        language = "语言",
        english = "English",
        chinese = "中文",
        forceLandscape = "强制横屏",
        gameRootPath = "游戏根目录",
        logPath = "日志导出路径",
        saveAndScan = "保存",
        scanDone = "已保存，返回主页后会自动重新扫描。",
        exportBackup = "导出设置备份",
        exportLogs = "导出日志",
        exported = "已导出",
        logsExported = "日志已导出",
        launchOriginal = "启动 KrKr2 原版",
        justNow = "刚刚",
        minutesAgoFmt = { n -> "${n}分钟前" },
        hoursAgoFmt = { n -> "${n}小时前" },
        daysAgoFmt = { n -> "${n}天前" },
        aboutVersion = "构建分支：launcher 重写",
        aboutDescription = "面向 KrKr2 / Kirikiri 引擎的轻量 Android 启动器。",
    )
}