name: Code Format Check

on:  
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - 'cpp/**'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main ]
    paths:
      - 'cpp/**'
      - 'CMakeLists.txt'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.20
        continue-on-error: true
        with:
          source: 'cpp'
          extensions: 'cpp,cc,h,hpp,inc'
          clangFormatVersion: 18